### ISSUE TITLE
Lack of Documentation

### ISSUE THREAD

**Issue by xexeo** [queirozfcom/rachinations#75]
You need to create enough documentation for the DSL to be developed and used. 

1. Development Manual
  It must contain an overall explanation and class diagrams.
  It must contain steps to: 
     Install in Linux and Windows machines
     Use GitHub
     Make tests, specs, rakes (not working in RubyMine now, at least for me)
2. User Manual
    You must describe the DSL use.
    Every "command" must be described, its parameters too

**Comment by queirozfcom** [comment]
I agree and I think this is important so I'll label it severity:HIGH
