### ISSUE TITLE
rake does not work?

### ISSUE THREAD

**Issue by xexeo** [queirozfcom/rachinations#76]
Can´t rake in RubyMine or main directory

Actually: 

No examples found

**Comment by queirozfcom** [comment]
Pode ser porque eu não estou usando o diretório padrão para testes. O senhor pode tentar rodar o comando `rake spec` e só `rake` no mesmo diretório onde o arquivo `Rakefile` está?

**Comment by xexeo** [comment]
H:\RubyMineProjects\rachinations>rake spec
DL is deprecated, please use Fiddle
C:/Ruby21-x64/bin/ruby.exe -I'C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rspec-suppo
rt-3.1.2/lib';'C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib' C:/R
uby21-x64/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern 'spec/**
{,/*/**}/*_spec.rb' --default-path testing/spec --color
No examples found.


Finished in 0 seconds (files took 0.1094 seconds to load)
0 examples, 0 failures

H:\RubyMineProjects\rachinations>rake
DL is deprecated, please use Fiddle
C:/Ruby21-x64/bin/ruby.exe -I'C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rspec-suppo
rt-3.1.2/lib';'C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib' C:/R
uby21-x64/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern 'spec/**
{,/*/**}/*_spec.rb' --default-path testing/spec --color
No examples found.


Finished in 0 seconds (files took 0.05213 seconds to load)
0 examples, 0 failures

H:\RubyMineProjects\rachinations>

**Comment by queirozfcom** [comment]
This was fixed by 6bc1ddfb36d9fd6cac914a7eaee08f4acf90a36c
