### ISSUE TITLE
Codigo que nao rodeu (trigger?)

### ISSUE THREAD

**Issue by xexeo** [queirozfcom/rachinations#78]
Seguindo exemplo do projeto final, isso não rodou direito, source nunca é ativado pelo s2 (quando chega algo lá)

r=diagram  'testa_trigger', mode: :verbose do

  pool 's1', :automatic , initial_value: 10 , mode: :push_any
  source 's4' , activation: :passive
  pool 's2', triggers: 's4'
  pool 's3'

  edge 's12' , from: 's1' , to: 's2'
  edge 's43', from: 's4' , to: 's3'

end

**Comment by queirozfcom** [comment]
a opção `triggers` eu adiei um pouco pois eu vou precisar resolver o #70 antes. Mas dá pra usar o `triggered_by` também, só que, em vez de setar isso no nó que *causa* o gatilhamento, precisa setar no nó que *é* gatilhado.

**Comment by queirozfcom** [comment]
Vou conseguir resolver isso antes de resolver #70 mas usuários só vão, por enquanto, poder referenciar nós já criados, o que torna o pensamento meio confuso.
